---
title: "Homework 8"
author: "Mary Anna Kivenson"
date: "4/7/2019"
output:
  html_document:
    highlight: pygments
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Assignment: 8.2, 8.4, 8.8, 8.16, 8.18

## 8.2 Baby weights, Part II. {.tabset .tabset-fade}

Exercise 8.1 introduces a data set on birth weight of babies.
Another variable we consider is parity, which is 0 if the child is the first born, and 1 otherwise.
The summary table below shows the results of a linear regression model for predicting the average
birth weight of babies, measured in ounces, from parity.

### Part A

Write the equation of the regression line.

### Part B

Interpret the slope in this context, and calculate the predicted birth weight of first borns and
others.

### Part C

Is there a statistically significant relationship between the average birth weight and parity?

## 8.4 Absenteeism. {.tabset .tabset-fade}

Researchers interested in the relationship between absenteeism from school
and certain demographic characteristics of children collected data from 146 randomly sampled students in rural New South Wales, Australia, in a particular school year. Below are three observations
from this data set.

The summary table below shows the results of a linear regression model for predicting the average
number of days absent based on ethnic background (eth: 0 - aboriginal, 1 - not aboriginal), sex
(sex: 0 - female, 1 - male), and learner status (lrn: 0 - average learner, 1 - slow learner).

### Part A

Write the equation of the regression line.

### Part B

Interpret each one of the slopes in this context.

### Part C

Calculate the residual for the first observation in the data set: a student who is aboriginal,
male, a slow learner, and missed 2 days of school.

### Part D

The variance of the residuals is 240.57, and the variance of the number of absent days for all
students in the data set is 264.17. Calculate the R2 and the adjusted R2. Note that there are
146 observations in the data set.


## 8.8 Absenteeism, Part II. {.tabset .tabset-fade}

Exercise 8.4 considers a model that predicts the number of days
absent using three predictors: ethnic background (eth), gender (sex), and learner status (lrn).
The table below shows the adjusted R-squared for the model as well as adjusted R-squared values
for all models we evaluate in the first step of the backwards elimination process.


## 8.16 Challenger disaster, Part I. {.tabset .tabset-fade}

On January 28, 1986, a routine launch was anticipated for
the Challenger space shuttle. Seventy-three seconds into the flight, disaster happened: the shuttle
broke apart, killing all seven crew members on board. An investigation into the cause of the
disaster focused on a critical seal called an O-ring, and it is believed that damage to these O-rings
during a shuttle launch may be related to the ambient temperature during the launch. The table
below summarizes observational data on O-rings for 23 shuttle missions, where the mission order
is based on the temperature at the time of the launch. Temp gives the temperature in Fahrenheit,
Damaged represents the number of damaged O-rings, and Undamaged represents the number of
O-rings that were not damaged.

### Part A

Each column of the table above represents a di↵erent shuttle mission. Examine these data
and describe what you observe with respect to the relationship between temperatures and
damaged O-rings.

### Part B

Failures have been coded as 1 for a damaged O-ring and 0 for an undamaged O-ring, and
a logistic regression model was fit to these data. A summary of this model is given below.
Describe the key components of this summary table in words.

### Part C

Write out the logistic model using the point estimates of the model parameters.

### Part D

Based on the model, do you think concerns regarding O-rings are justified? Explain.


## 8.18 Challenger disaster, Part II. {.tabset .tabset-fade}

### Part A

The data provided in the previous exercise are shown in the plot. The logistic model fit to
these data may be written as

$log(\frac{\hat{p}}{1-\hat{p}}) = 11.6630 - 0.2162 * Temperature$

where $\hat{p}$ is the model-estimated probability that an O-ring will become damaged. Use the
model to calculate the probability that an O-ring will become damaged at each of the following
ambient temperatures: 51, 53, and 55 degrees Fahrenheit. The model-estimated probabilities
for several additional ambient temperatures are provided below, where subscripts indicate the
temperature:
$\hat{p}_{57}$ = 0.341 $\hat{p}_{59}$ = 0.251 $\hat{p}_{61}$ = 0.179 $\hat{p}_{63}$ = 0.124
$\hat{p}_{65}$ = 0.084 $\hat{p}_{67}$ = 0.056 $\hat{p}_{69}$ = 0.037 $\hat{p}_{71}$ = 0.024

### Part B

Add the model-estimated probabilities from part (a) on the plot, then connect these dots using
a smooth curve to represent the model-estimated probabilities.

### Part C

Describe any concerns you may have regarding applying logistic regression in this application,
and note any assumptions that are required to accept the model’s validity.