---
title: "DATA 606 Homework 4"
author: "Mary Anna Kivenson"
date: "3/11/2019"
output:
  html_document:
    highlight: pygments
    theme: united
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(openintro)
```

Assignment: 4.4, 4.14, 4.24, 4.26, 4.34, 4.40, 4.48

##4.4  Heights of adults.   {.tabset .tabset-fade}  
Researchers studying anthropometry collected body girth measurements
and skeletal diameter measurements, as well as age, weight, height and gender, for 507 physically
active individuals. The histogram below shows the sample distribution of heights in centimeters.  


### Part A  
What is the point estimate for the average height of active individuals? What about the
median? (See the next page for parts (b)-(e).)


### Part B  
What is the point estimate for the standard deviation of the heights of active individuals?
What about the IQR?


### Part C  
Is a person who is 1m 80cm (180 cm) tall considered unusually tall? And is a person who is
1m 55cm (155cm) considered unusually short? Explain your reasoning.


### Part D
The researchers take another random sample of physically active individuals. Would you
expect the mean and the standard deviation of this new sample to be the ones given above?
Explain your reasoning.


### Part E
The sample means obtained are point estimates for the mean height of all active individuals,
if the sample of individuals is equivalent to a simple random sample. What measure do we
use to quantify the variability of such an estimate (Hint: recall that $SD_\bar{x} = \frac{\sigma}{\sqrt{n}}$)? 
Compute this quantity using the data from the original sample under the condition that the data are a
simple random sample.


##

##4.14 Thanksgiving spending, Part I. {.tabset .tabset-fade}
The 2009 holiday retail season, which kicked off on
November 27, 2009 (the day after Thanksgiving), had been marked by somewhat lower self-reported
consumer spending than was seen during the comparable period in 2008. To get an estimate
of consumer spending, 436 randomly sampled American adults were surveyed. Daily consumer
spending for the six-day period after Thanksgiving, spanning the Black Friday weekend and Cyber
Monday, averaged \$84.71. A 95% confidence interval based on this sample is (\$80.31, $89.11).
Determine whether the following statements are true or false, and explain your reasoning.


### Part A  
We are 95% confident that the average spending of these 436 American adults is between
\$80.31 and $89.11.

### Part B  
This confidence interval is not valid since the distribution of spending in the sample is right
skewed.

### Part C  
95% of random samples have a sample mean between \$80.31 and $89.11.

### Part D 
We are 95% confident that the average spending of all American adults is between \$80.31 and
$89.11.

### Part E  
A 90% confidence interval would be narrower than the 95% confidence interval since we don’t
need to be as sure about our estimate.

### Part F  
In order to decrease the margin of error of a 95% confidence interval to a third of what it is
now, we would need to use a sample 3 times larger.

### Part G  
The margin of error is 4.4.


##

##4.24 Gifted children, Part I.  {.tabset .tabset-fade}
Researchers investigating characteristics of gifted children collected data from schools in a
large city on a random sample of thirty-six children who were identified as gifted children 
soon after they reached the age of four. The following histogram shows the distribution of the
ages (in months) at which these children first counted to 10 successfully. Also provided are
some sample statistics.

### Part A
Are conditions for inference satisfied?

### Part B
Suppose you read online that children first count to 10 successfully when they are 32 months
old, on average. Perform a hypothesis test to evaluate if these data provide convincing evidence
that the average age at which gifted children fist count to 10 successfully is less than the general
average of 32 months. Use a significance level of 0.10.

### Part C
Interpret the p-value in context of the hypothesis test and the data.

### Part D
Calculate a 90% confidence interval for the average age at which gifted children first count to
10 successfully.

### Part E
Do your results from the hypothesis test and the confidence interval agree? Explain.

##

##4.26 Gifted children, Part II.  {.tabset .tabset-fade}

### Part A
Perform a hypothesis test to evaluate if these data provide convincing evidence that the average
IQ of mothers of gifted children is different than the average IQ for the population at large,
which is 100. Use a significance level of 0.10.

### Part B
Calculate a 90% confidence interval for the average IQ of mothers of gifted children.

### Part C
Do your results from the hypothesis test and the confidence interval agree? Explain.

##

##4.34 CLT.  {.tabset .tabset-fade}  
Define the term “sampling distribution” of the mean, and describe how the shape,
center, and spread of the sampling distribution of the mean change as sample size increases.

##

##4.40 CFLBs.  {.tabset .tabset-fade}  
A manufacturer of compact fluorescent light bulbs advertises that the distribution
of the lifespans of these light bulbs is nearly normal with a mean of 9,000 hours and a standard
deviation of 1,000 hours.

### Part A
What is the probability that a randomly chosen light bulb lasts more than 10,500 hours?

### Part B
Describe the distribution of the mean lifespan of 15 light bulbs.

### Part C
What is the probability that the mean lifespan of 15 randomly chosen light bulbs is more than
10,500 hours?

### Part D
Sketch the two distributions (population and sampling) on the same scale.

### Part E
Could you estimate the probabilities from parts (a) and (c) if the lifespans of light bulbs had
a skewed distribution?  

##

##4.48 Same observation, different sample size.  {.tabset .tabset-fade}
Suppose you conduct a hypothesis test based
on a sample where the sample size is n = 50, and arrive at a p-value of 0.08. You then refer back
to your notes and discover that you made a careless mistake, the sample size should have been
n = 500. Will your p-value increase, decrease, or stay the same? Explain.  

##